# name: ğŸš€ Deploy to VPS (Docker)

# on:
#   push:
#     branches: [main]

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: ğŸ“‚ Checkout code
#         uses: actions/checkout@v3

#       - name: ğŸ” Setup SSH
#         uses: webfactory/ssh-agent@v0.8.0
#         with:
#           ssh-private-key: ${{ secrets.OCI_SSH_KEY }}

#       - name: ğŸš€ Deploy to VPS
#         run: |
#           ssh -o StrictHostKeyChecking=no ${{ secrets.OCI_USER }}@${{ secrets.OCI_HOST }} << 'EOF'
#             set -e

#             echo "ğŸ“ Cloning/Updating repo"
#             cd ${{ secrets.OCI_APP_DIR }} || exit 1
#             git pull origin main

#             echo "ğŸ³ Rebuilding Docker container..."
#             docker stop my-nextjs || true
#             docker rm my-nextjs || true
#             docker build -t nextjs-app .
#             docker run -d -p 3000:3000 --name my-nextjs nextjs-app

#             echo "âœ… Deployment Complete!"
#           EOF